name: 'taxi_rides_ny'
version: '1.0.0'
config-version: 2

profile: 'default'

# aqui é um mapeamento entre os tipos de objetos e as pastas do projeto que irão contê-los
# geralmente isso não se altera
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # pastas que irão conter os códigos compilados
clean-targets:         # pastas a serem removidas pelo comando 'dbt clean'
  - "target"
  - "dbt_packages"

# documentação para configurar modelos: https://docs.getdbt.com/docs/configuring-models

# todos os modelos da pasta 'example' serão materializados como tabelas
# a materialização default é como view
# posso definir a materialização tanto por aqui quanto individualmente em cada modelo (`{{ config(...) }}` macro)
models:
  taxi_rides_ny:
    # Applies to all files under models/example/
    example:
      +materialized: table
