version: 2

# o 'generate model' cria uma BASE DE CÓDIGO para que eu possa continuar o desenvolvimento do modelo a partir da fonte de dados

sources:
  - name: staging
    database: taxi-rides-ny-448023
    schema: demo_dataset

    tables:
      - name: green_tripdata
      - name: yellow_tripdata

# isso foi gerado com o 'codegen'
models:
  - name: stg_green_tripdata
    description: ""
    columns:
      - name: tripid
        data_type: string
        description: ""
        tests:
                - unique: # checando se os valores são únicos
                    severity: warn # apenas aviso, sem abortar
                - not_null: # checando se os valores são not null
                    severity: warn

      - name: vendorid
        data_type: int64
        description: ""

      - name: ratecodeid
        data_type: int64
        description: ""

      - name: pickup_locationid
        data_type: int64
        description: ""
        tests:
              - relationships: # checando se há relacionamento com a tabela 'taxi_zone_lookup' 
                  to: ref('taxi_zone_lookup')
                  field: locationid
                  severity: warn

      - name: dropoff_locationid
        data_type: int64
        description: ""
        tests:
              - relationships: # checando se há relacionamento com a tabela 'taxi_zone_lookup'
                  to: ref('taxi_zone_lookup')
                  field: locationid
                  severity: warn

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: store_and_fwd_flag
        data_type: string
        description: ""

      - name: passenger_count
        data_type: int64
        description: ""

      - name: trip_distance
        data_type: numeric
        description: ""

      - name: trip_type
        data_type: int64
        description: ""

      - name: fare_amount
        data_type: numeric
        description: ""

      - name: extra
        data_type: numeric
        description: ""

      - name: mta_tax
        data_type: numeric
        description: ""

      - name: tip_amount
        data_type: numeric
        description: ""

      - name: tolls_amount
        data_type: numeric
        description: ""

      - name: ehail_fee
        data_type: numeric
        description: ""

      - name: improvement_surcharge
        data_type: numeric
        description: ""

      - name: total_amount
        data_type: numeric
        description: ""

      - name: payment_type
        data_type: int64
        description: ""
        tests: 
              - accepted_values: # checando se os valores são permitidos (varável está definida no yaml do projeto)
                  values: "{{ var('payment_type_values') }}"
                  severity: warn
                  quote: false

      - name: payment_type_description
        data_type: string
        description: ""

  - name: stg_yellow_tripdata
    description: ""
    columns:
      - name: tripid
        data_type: string
        description: ""

      - name: vendorid
        data_type: int64
        description: ""

      - name: ratecodeid
        data_type: int64
        description: ""

      - name: pickup_locationid
        data_type: int64
        description: ""

      - name: dropoff_locationid
        data_type: int64
        description: ""

      - name: pickup_datetime
        data_type: timestamp
        description: ""

      - name: dropoff_datetime
        data_type: timestamp
        description: ""

      - name: store_and_fwd_flag
        data_type: string
        description: ""

      - name: passenger_count
        data_type: int64
        description: ""

      - name: trip_distance
        data_type: numeric
        description: ""

      - name: trip_type
        data_type: int64
        description: ""

      - name: fare_amount
        data_type: numeric
        description: ""

      - name: extra
        data_type: numeric
        description: ""

      - name: mta_tax
        data_type: numeric
        description: ""

      - name: tip_amount
        data_type: numeric
        description: ""

      - name: tolls_amount
        data_type: numeric
        description: ""

      - name: ehail_fee
        data_type: numeric
        description: ""

      - name: improvement_surcharge
        data_type: numeric
        description: ""

      - name: total_amount
        data_type: numeric
        description: ""

      - name: payment_type
        data_type: int64
        description: ""

      - name: payment_type_description
        data_type: string
        description: ""