version: 2

# o 'generate model' cria uma BASE DE CÓDIGO para que eu possa continuar o desenvolvimento do modelo a partir da fonte de dados

sources:
  - name: staging
    database: taxi-rides-ny-448023
    schema: demo_dataset

    tables:
      - name: green_tripdata
      - name: yellow_tripdata